name: GitHub Actions Practica
on: [push]
jobs:
  Explorando-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"
      - run: echo "El trabajo se está ejecutando en un servidor ${{ runner.os }} hospedado en GitHub"
      - run: echo "El nombre de la rama es: ${{ github.ref }} y tu repositorio es: ${{ github.repository }}."
      - run: echo "Se está verificando el código del repositorio"
      - run: echo "El repositorio ${{ github.repository }} ha sido colocado al runner."
      - run: echo "El flujo de trabajo está listo para verificar el código en el runner."
      - run: echo "El estado del trabajo es: ${{ job.status }}."